(export (version D)
  (design
    (source "automated_solenoid_switches.kicad_sch")
    (date "2026-09-09")
    (tool "Eeschema 8.0.0"))
  (components
    (comp (ref ISO1)
      (value "Optocoupler_4Ch")
      (footprint "Package_DIP:DIP-16_W7.62mm")
      (libsource (lib "Isolator") (part "ILQ74") (description "Quad Optocoupler, Phototransistor Output")))
    (comp (ref Q1)
      (value "Solenoid_Driver_MOSFET")
      (footprint "Package_TO_SOT_THT:TO-220-3_Vertical")
      (libsource (lib "Device") (part "Q_NMOS_GDS") (description "N-MOSFET transistor, Gate/Drain/Source")))
    (comp (ref D1)
      (value "Flyback_Protection")
      (footprint "Diode_THT:D_DO-41_P10.16mm_Horizontal")
      (libsource (lib "Device") (part "D") (description "Flyback suppression diode")))
    (comp (ref CONN_PWR1)
      (value "Hydraulic_24V_In")
      (footprint "TerminalBlock_Phoenix:TerminalBlock_Phoenix_MKDS-1,5-2_1x02_P3.50mm_Horizontal")
      (libsource (lib "Connector") (part "Conn_01x02_Female") (description "High-current power connection")))
    (comp (ref SOL1)
      (value "Manifold_Solenoid_Coil")
      (footprint "Connector_Phoenix:PhoenixContact_MSTBVA_2.5_2-G")
      (libsource (lib "Device") (part "Solenoid") (description "Solenoid Actuator Coil"))))
  (nets
    (net (code 1) (name "GND_ISO")
      (node (ref ISO1) (pin 2))
      (node (ref ISO1) (pin 4)))
    (net (code 2) (name "/UNIVAC_SOL_CMD")
      (node (ref ISO1) (pin 1)))
    (net (code 3) (name "GND_24V")
      (node (ref ISO1) (pin 9))
      (node (ref Q1) (pin 3))
      (node (ref CONN_PWR1) (pin 2)))
    (net (code 4) (name "+24V")
      (node (ref CONN_PWR1) (pin 1))
      (node (ref D1) (pin 2))
      (node (ref SOL1) (pin 1))
      (node (ref ISO1) (pin 16)))
    (net (code 5) (name "/GATE_DRIVE")
      (node (ref ISO1) (pin 10))
      (node (ref Q1) (pin 1)))
    (net (code 6) (name "/SOLENOID_RETURN")
      (node (ref Q1) (pin 2))
      (node (ref D1) (pin 1))
      (node (ref SOL1) (pin 2)))))
